"""
BaseStrategy - Abstract base class for all trading strategies.
Every strategy inherits from this and implements generate_signal().
"""

import json
import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Optional

import pandas as pd

from agent.config import STRATEGIES_CONFIG_DIR

logger = logging.getLogger(__name__)


class SignalType(Enum):
    """Trading signal types."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"       # No action


@dataclass
class Signal:
    """A trading signal generated by a strategy."""
    type: SignalType
    strategy: str           # Strategy name
    symbol: str             # Ticker
    confidence: float       # 0.0 - 1.0
    entry_price: float      # Suggested entry price
    stop_loss: float        # Mandatory stop loss price
    take_profit: float      # Target price
    reason: str             # Human-readable reason
    indicators: dict        # Indicator values at signal time

    @property
    def risk_reward_ratio(self) -> float:
        """Calculate risk/reward ratio."""
        risk = abs(self.entry_price - self.stop_loss)
        reward = abs(self.take_profit - self.entry_price)
        if risk == 0:
            return 0
        return reward / risk

    def to_dict(self) -> dict:
        return {
            "type": self.type.value,
            "strategy": self.strategy,
            "symbol": self.symbol,
            "confidence": self.confidence,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "risk_reward": round(self.risk_reward_ratio, 2),
            "reason": self.reason,
            "indicators": self.indicators,
        }


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    Each strategy:
    - Has fixed parameters (loaded from JSON config)
    - Has activation conditions (changeable by Claude Coach)
    - Generates BUY/SELL/HOLD signals based on indicator data
    - Never changes its own parameters
    """

    def __init__(self, config_name: str):
        """
        Args:
            config_name: Name of the JSON config file (without .json)
                        e.g., "rsi_macd" loads strategies_config/rsi_macd.json
        """
        self.config_name = config_name
        self.config = self._load_config()
        self.name = self.config["name"]
        self.enabled = self.config.get("enabled", True)
        self.params = self.config["params"]
        self.activation_conditions = self.config["activation_conditions"]
        self.timeframe = self.config.get("timeframe", "5Min")

    def _load_config(self) -> dict:
        """Load strategy config from JSON file."""
        config_path = STRATEGIES_CONFIG_DIR / f"{self.config_name}.json"
        if not config_path.exists():
            raise FileNotFoundError(f"Strategy config not found: {config_path}")

        with open(config_path) as f:
            config = json.load(f)

        logger.info(f"Loaded config for {config.get('name', self.config_name)}")
        return config

    def reload_config(self):
        """Reload config from disk (after Claude Coach updates it)."""
        self.config = self._load_config()
        self.enabled = self.config.get("enabled", True)
        self.activation_conditions = self.config["activation_conditions"]
        logger.info(f"Reloaded config for {self.name}")

    def is_active(self, session: str, market_condition: str,
                  indicators: Optional[dict] = None) -> bool:
        """
        Check if this strategy should be active right now.
        Based on activation_conditions (which Claude Coach can change).

        Args:
            session: Current session name (opening, midday, power_hour)
            market_condition: Current market state (TRENDING_UP, RANGING, etc.)
            indicators: Optional dict of current indicator values

        Returns:
            True if strategy should be active
        """
        if not self.enabled:
            return False

        conditions = self.activation_conditions

        # Check session
        allowed_sessions = conditions.get("sessions", [])
        if allowed_sessions and session not in allowed_sessions:
            return False

        # Check market condition
        allowed_conditions = conditions.get("market_conditions", [])
        if allowed_conditions and market_condition not in allowed_conditions:
            return False

        # Check ADX bounds (if specified)
        if indicators:
            adx = indicators.get("adx", 0)
            if "adx_min" in conditions and adx < conditions["adx_min"]:
                return False
            if "adx_max" in conditions and adx > conditions["adx_max"]:
                return False

            # Check VIX bounds
            vix = indicators.get("vix", 0)
            if "vix_max" in conditions and vix > conditions["vix_max"]:
                return False

        return True

    @abstractmethod
    def generate_signal(self, df: pd.DataFrame, symbol: str) -> Signal:
        """
        Analyze data and generate a trading signal.

        Args:
            df: DataFrame with OHLCV + all indicators (from IndicatorCalculator)
            symbol: Stock ticker

        Returns:
            Signal with BUY, SELL, or HOLD
        """
        pass

    def _hold_signal(self, symbol: str, reason: str = "No signal") -> Signal:
        """Convenience method to create a HOLD signal."""
        return Signal(
            type=SignalType.HOLD,
            strategy=self.name,
            symbol=symbol,
            confidence=0,
            entry_price=0,
            stop_loss=0,
            take_profit=0,
            reason=reason,
            indicators={},
        )

    def __repr__(self):
        return f"<{self.name} enabled={self.enabled}>"
